---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/cordeiro/public_html
    - if [ ! -d "$DEPLOYPATH" ]; then export DEPLOYPATH=$HOME/public_html; fi
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R dist/* $DEPLOYPATH/
    - /bin/cp -f dist/.htaccess $DEPLOYPATH/
