name: 🚀 Deploy Website via FTP

on:
  push:
    branches:
      - main  # Change to 'master' if your branch name is master

jobs:
  web-deploy:
    name: 🎉 Sync Files to cPanel
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
